// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vdualwavegen.cpp"
#include "Vdualwavegen___024root__DepSet_h7c31f02b__0.cpp"
#include "Vdualwavegen__Trace__0.cpp"
#include "Vdualwavegen___024root__Slow.cpp"
#include "Vdualwavegen___024root__DepSet_h7c31f02b__0__Slow.cpp"
#include "Vdualwavegen__Syms.cpp"
#include "Vdualwavegen__Trace__0__Slow.cpp"
